name: Send Webhook Payload via Email

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-event

jobs:
  process-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Extract payload
        id: extract-payload
        run: |
          echo "::set-output name=payload::${{ github.event.client_payload }}"

      - name: Send email with payload
        env:
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_APP_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: |
          python <<EOF
          import smtplib
          from email.mime.text import MIMEText

          # Email sender and recipient
          sender = "${{ secrets.ICLOUD_EMAIL }}"
          recipient = "bobbypanchal@me.com"

          # Email subject and body
          subject = "Webhook Payload"
          body = f"Payload received: ${{ steps.extract-payload.outputs.payload }}"

          # Set up email
          msg = MIMEText(body)
          msg["Subject"] = subject
          msg["From"] = sender
          msg["To"] = recipient

          # Send email via iCloud SMTP server
          with smtplib.SMTP_SSL("smtp.mail.me.com", 465) as server:
              server.login(sender, "${{ secrets.ICLOUD_PASSWORD }}")
              server.sendmail(sender, recipient, msg.as_string())
          EOF
