name: Webhook Payload Processor

on:
  repository_dispatch:
    types:
      - trigger-email

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log Received Payload
        run: |
          echo "Event Type: ${{ github.event.action }}"
          echo "Payload: ${{ toJson(github.event.client_payload) }}"

      - name: Process Payload
        run: |
          echo "Processing the payload data..."
          echo "Message: ${{ github.event.client_payload.message }}"
          echo "Custom Key 1: ${{ github.event.client_payload.key1 }}"
          echo "Custom Key 2: ${{ github.event.client_payload.key2 }}"

      # Add any additional steps you need to process the payload
